### ISSUE TITLE
Vue3 (Composition API) Error: Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by bilalaslam777** [csvbox-io/vue-adapter#1]
I am getting following error in Vue3 using composition APIs. F

Property "$createElement" was accessed during render but is not defined on instance.

Property "_self" was accessed during render but is not defined on instance.

TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (CSVBoxButton.vue?4726:1:66)
    at renderComponentRoot (runtime-core.esm-bundler.js:896:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5580:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at instance.update (runtime-core.esm-bundler.js:5694:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5708:9)
    at mountComponent (runtime-core.esm-bundler.js:5490:9)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
    at mountChildren (runtime-core.esm-bundler.js:5234:13)
    

TypeError: Cannot set properties of undefined (setting 'onload')
    at Proxy.mounted (CSVBoxButton.vue:121:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2687:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:358:32)
    at flushJobs (runtime-core.esm-bundler.js:403:9)

I copied the code from your documentation and replaced the licenseKey with a real one.

**Comment by mariela-plaza** [comment]
Same here, the error is still happening. I am trying to work with the options API in vue3 and it still gives me errors, does the same happen to you?
